version: '3.8'

services:
  app:
    image: node:14   # You can specify the Node.js version you need
    working_dir: /usr/src/app
    command: npm start
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"  # Map your application's port to the host
    environment:
      NODE_ENV: development
