version: '3.8'

services:
  app:
    image: node:18
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    volumes:
      - ./app:/usr/src/app
    ports:
      - "1234:3000"
    environment:
      NODE_ENV: development
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=$TRAEFIK_NETWORK"
      - "traefik.http.routers.batsli-http.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.batsli-http.entryPoints=web"
      - "traefik.http.routers.batsli-http.middlewares=batsli-https-redirect"
      - "traefik.http.middlewares.batsli-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.batsli-https.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.batsli-https.entryPoints=websecure"
      - "traefik.http.routers.batsli-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.batsli-https.tls=true"
      - "traefik.http.services.batsli-https.loadbalancer.server.port=80"
      
networks:
  default:
    driver: bridge
  proxy:
    external: true
    name: $TRAEFIK_NETWORK