version: '3.8'

services:
  app:
    image: node:18   # Use Node.js v18
    working_dir: /usr/src/app
    command: sh -c "npm install && npm start"
    volumes:
      - ./app:/usr/src/app
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development

